export default effects = [
            {
                id: 1,
                title: "Pencil Sketch B/W",
                effect: "pencilsketchBW",
                tap: false,
                InnerPropertyexist: true,
                background:"pencil-sketch-BW.jpg",
                initial_param:0.04,
                parameterStep:0.01,
                maximumParameterValue:0.1,
                parameterName:"Shade Factor"
            },
            {
                id: 2,
                title: "Water Color",
                effect: "watercolour",
                tap: false,
                InnerPropertyexist: true,
                background:"",
                initial_param:0.4,
                parameterStep:0.1,
                maximumParameterValue:1,
                parameterName:"Stroke Size"
            },
            {
                id: 3,
                title: "Oil Paint",
                effect: "oilpaint",
                tap: false,
                InnerPropertyexist: true,
                background:"Oil_paint.jpg",
                initial_param:20,
                parameterStep:1,
                maximumParameterValue:100,
                parameterName:"Stroke Size"
            },
            {
                id: 4,
                title: "Pointlissim",
                effect: "pointlissim",
                tap: false,
                InnerPropertyexist: true,
                background:"Pointlissim.jpg",
                initial_param:10,
                parameterStep:1,
                maximumParameterValue:20,
                parameterName:"Brush Stroke"
            },
            {
                id: 5,
                title: "Pencil Sketch colour",
                effect: "pencilsketchColor",
                tap: false,
                InnerPropertyexist: true,
                background:"pencil-sketch-Colour.jpg",
                initial_param:0.04,
                parameterStep:0.01,
                maximumParameterValue:0.1,
                parameterName:"Shade Factor"
            },
            {
                id: 6,
                title: "Cartoon",
                effect: "cartoon",
                tap: false,
                InnerPropertyexist: true,
                background:"",
                initial_param:6,
                parameterStep:3,
                maximumParameterValue:25,
                parameterName:"Stroke Size"
            },
            {
                id: 7,
                title: "glass Filter",
                effect: "glass",
                tap: false,
                InnerPropertyexist: false,
                background:"",
                initial_param:0,
                parameterStep:0,
                maximumParameterValue:0,
                parameterName:"NA"
            },
            {
                id: 8,
                title: "Dog Filter",
                effect: "dog",
                tap: false,
                InnerPropertyexist: false,
                background:"",
                initial_param:0,
                parameterStep:0,
                maximumParameterValue:0,
                parameterName:"NA"
            },
            {
                id: 9,
                title: "Cat Filter",
                effect: "cat",
                tap: false,
                InnerPropertyexist: false,
                background:"",
                initial_param:0,
                parameterStep:0,
                maximumParameterValue:0,
                parameterName:"NA"
            },
            {
                id: 10,
                title: "Edge Preserving",
                effect: "edgePreserving",
                tap: false,
                InnerPropertyexist: true,
                background:"",
                initial_param:20,
                parameterStep:1,
                maximumParameterValue:100,
                parameterName:"Stroke Size"
            },

        ]